// Generated by JProtoc(https://github.com/matrix3d/jProtoc)
// source: /awesome.proto
package awesomepackage{
import jprotoc.Message;
import jprotoc.Int64;
public class AwesomeMessage extends Message{

private var _awesome_field:String;
public function get awesome_field():String {return _awesome_field;}
public function set awesome_field(value:String):void { _awesome_field = value; setHas(1); }


public function get has_awesome_field():Boolean{return has(1);}

public function AwesomeMessage(){var pname:String = "awesomepackage::AwesomeMessage";mMessageEncode = messageEncode[pname] =messageEncode[pname]||{1:["awesome_field",1,9]};init();}
}}